"""Add Google Calendar sync fields

Revision ID: c55130e37ce3
Revises: 
Create Date: 2025-07-09 14:00:55.617659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55130e37ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), nullable=True),
    sa.Column('bathrooms', sa.FLOAT(), nullable=True),
    sa.Column('square_footage', sa.INTEGER(), nullable=True),
    sa.Column('lot_size', sa.FLOAT(), nullable=True),
    sa.Column('year_built', sa.INTEGER(), nullable=True),
    sa.Column('property_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rent_estimate', sa.FLOAT(), nullable=True),
    sa.Column('price_estimate', sa.FLOAT(), nullable=True),
    sa.Column('price_per_sqft', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
